# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Health_And_Matching' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Health_And_Matching
  pod 'Alamofire', '~> 4.8.2'  
  pod "GMStepper"
end
